language: python
python:
  - "2.7_with_system_site_packages"

cache:
  - apt
  - pip

addons:
  apt:
    packages:
      - python-alsaaudio
      - git
      - mercurial

install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  - "pip install coverage"

before_script: 
  - "export AUDIODEV=null"
  - "sudo modprobe snd-dummy"

script:
  - nosetests --verbosity=3

after_success:
  coveralls
